version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://user:password@db:3306/game_library?connect_timeout=300
      - NODE_ENV=production
    networks:
      - app-network
    volumes:
      - ./prisma:/app/prisma
    
  db-init:
    image: mariadb:10.6
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./prisma/migrations:/migrations
    environment:
      - MYSQL_PWD=rootpassword
    command: >
      bash -c '
      sleep 10 &&
      mysql -h db -u root -e "SET GLOBAL max_allowed_packet=67108864;" &&
      echo "Running migrations..." &&
      cat /migrations/20250425000000_init/migration.sql | mysql -h db -u root game_library &&
      echo "Migrations completed successfully" &&
      exit 0
      '
    networks:
      - app-network

  db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=game_library
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 2s
      timeout: 5s
      retries: 20
      start_period: 10s
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - db

volumes:
  mariadb-data:
    driver: local

networks:
  app-network:
    driver: bridge 