services:
  app:
    image: node:20-alpine
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - playvault-data:/data
    command: >
      sh -c "
        echo 'Setting up PlayVault with SQLite...'
        cd /tmp
        
        # Klone das Repository
        apk add --no-cache git
        git clone https://github.com/netz-sg/PlayVault.git
        cd playvault
        
        # Ändere Prisma zu SQLite
        sed -i 's/provider = \"mysql\"/provider = \"sqlite\"/g' prisma/schema.prisma
        sed -i 's/url.*=\".*\"/url = \"file:\\/\\/\\/data\\/playvault.db\"/g' prisma/schema.prisma
        sed -i '/Text/! s/@db.Text//g' prisma/schema.prisma
        
        # Installiere Abhängigkeiten und baue die App
        npm install --force
        npx prisma generate
        npm run build
        
        # Migriere die Datenbank
        npx prisma migrate deploy
        
        # Starte die App
        npm start
      "

volumes:
  playvault-data:
    driver: local 